use_frameworks!

platform :ios, '8.0'

target 'ZebraPrintSDK_Example' do
  pod 'ZebraPrintSDK', :path => '../'

  target 'ZebraPrintSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
